typescript implementation
silinternational/cover-ui pull request #127
Opened 2021-09-13 19:09 UTC by RussellChamp

* Rename all the js files to ts files
* Update all the svelte components to add `lang="ts"` to the script line
* Added necessary rollup build options
* Tweaked a few components to make them happy

2021-09-13 20:00 UTC, hobbitronics commented on tsconfig.json
> +{
I guess I will have to read the docs to understand this part, but just was curioiu why "__sapper__/*" is here.

2021-09-13 20:10 UTC, hobbitronics approved these changes
Looks pretty straightforward so far.

2021-09-13 21:03 UTC, forevermatt commented on rollup.config.js
> +		nodePolyfills(),
What were the node polyfills needed for?

2021-09-13 21:05 UTC, forevermatt commented on src/analytics/index.ts
> +  // TODO: get the dataLayer references to play nicer with ts
If it simplifies things, feel free to leave selected files (like this one) as `.js` instead of `.ts`. It's okay if we leave some plain JavaScript files in place, especially for files we won't be frequently changing or importing into other files.

2021-09-13 21:09 UTC, forevermatt commented on src/data/index.ts
> +export async function UPDATE(uri: string, body) { return await customFetch('put'   , uri, body) }
Did you mean to also change this `body` to `body: any`? I wasn't sure if this `UPDATE()` or the above `CREATE()` was more in line with the desired outcome here.

2021-09-13 21:10 UTC, forevermatt commented on src/data/index.ts
> +type FetchMethod = 'post' | 'get' | 'put' | 'delete';
Ahhh.... so _that's_ how you do custom types for that sort of thing. TIL!

2021-09-13 21:14 UTC, forevermatt commented on ts.errors
> +
Looks like you'll want to delete this... and possibly add it to `.gitignore`? I'm not sure whether it was autogenerated or was just concat'd to a file for debugging purposes.

2021-09-13 21:16 UTC, forevermatt requested changes
Mostly looks good, just a few questions and one file to delete.

2021-09-14 13:06 UTC, RussellChamp commented on tsconfig.json
> +{
ah, i think that was just a copy pasta that would be more applicable to other svelte apps

2021-09-14 13:07 UTC, RussellChamp commented on rollup.config.js
> +		nodePolyfills(),
i think that was due to the calls to `process` in analytics

2021-09-14 13:08 UTC, RussellChamp commented on src/analytics/index.ts
> +  // TODO: get the dataLayer references to play nicer with ts
either way is probably fine. i was on a roll here, though.

2021-09-14 13:10 UTC, RussellChamp commented on src/data/index.ts
> +export async function UPDATE(uri: string, body) { return await customFetch('put'   , uri, body) }
elsewhere in the code, `CREATE` was being called with only 1 parameter and missing the `body` parameter and caused ts to go "hey that doesn't seem right". I just put a bandaid on things for now. we can come back and do this "right" later.

2021-09-14 13:10 UTC, RussellChamp commented on src/data/index.ts
> +type FetchMethod = 'post' | 'get' | 'put' | 'delete';
yup! that's right!

2021-09-14 13:10 UTC, RussellChamp commented on ts.errors
> +
doh! yeah, i just wrote out some of the error lines to a temp file for reference. i'll squash that

2021-09-14 13:17 UTC, merged