Fix edit claim
silinternational/cover-ui pull request #140
Opened 2021-09-17 19:14 UTC by hobbitronics

The formData was just being sent to updateClaim, but needed to be split up, parsed and sent to updateClaim and updateClaimItem.

The api will need to add fields to updateClaim.

2021-09-17 19:18 UTC, forevermatt commented on src/data/claims.ts
> +    // fmv: claimItemData.fairMarketValueUSD,
This will probably need to be converted to dollars (used in the UI code) to cents (what the API typically expects for money fields), just as a heads-up. We have a `convertToCents()` method in our money helper for exactly that purpose.

Same with the other `...USD` local variables we are sending to the API.

2021-09-17 19:18 UTC, forevermatt commented on src/data/claims.ts
> +    // item_id: claimItemData.stringNumber,
Looks like this `stringNumber` was supposed to be `item_id`, I think.

2021-09-17 19:20 UTC, forevermatt commented on src/pages/claims/[claimId]/edit.svelte
> +  const editedClaimData = {
I think we've been doing this mapping/adjusting of form values in the functions that actually call the API and update our stores (like `updateClaim()`). Was there an advantage to doing that here in the page's code instead?

2021-09-17 20:00 UTC, hobbitronics commented on src/pages/claims/[claimId]/edit.svelte
> +  const editedClaimData = {
since we are using updateClaimItem, but with data from the claimForm which was originally for new claims and the createClaim endpoint I had to use an intermediate parsing step. I should be able to eliminate if for updateClaim though since we only use that once.

2021-09-17 20:17 UTC, hobbitronics commented on src/data/claims.ts
> +    // item_id: claimItemData.stringNumber,
I've invented a new type for js.

2021-09-17 20:17 UTC, hobbitronics commented on src/pages/claims/[claimId]/edit.svelte
> +  const editedClaimData = {
looks like I was able to eliminate mostly for both.

2021-09-17 20:39 UTC, hobbitronics commented on src/pages/claims/[claimId]/edit.svelte
> +  const editedClaimData = {
I am wondering if this would be better though, but unsure what the api will do with it.
```
    repairActual: null,
    replaceActual: null,
```

2021-09-20 14:58 UTC, RussellChamp reviewed
code lgtm

2021-09-20 21:49 UTC, forevermatt commented on src/pages/claims/[claimId]/edit.svelte
> +  const editedClaimItemData = {
I think it would be good to do even this in the `updateClaimItem()` method, so that any other code that calls `updateClaimItem()` doesn't have to also implement this edit.

2021-09-20 21:49 UTC, forevermatt commented on src/pages/claims/[claimId]/edit.svelte
> +  await updateClaimItem(ClaimItemId, editedClaimItemData)
```suggestion
  await updateClaimItem(claimItemId, editedClaimItemData)
```

2021-09-20 21:51 UTC, forevermatt reviewed
Final comments added. Almost there, thanks! 🙂  (Sorry I've once again been so slow to finish reviewing this...)

2021-09-21 14:35 UTC, forevermatt requested changes
The only two remaining things I see are moving the `repairActual: 0, replaceActual: 0,` bit down into `updateClaimItem()` and then lowercasing the "c" on the "ClaimItemId" variable.

2021-09-21 20:26 UTC, forevermatt approved these changes

2021-09-21 20:35 UTC, merged