fix item coverage submission
silinternational/cover-ui pull request #141
Opened 2021-09-20 16:45 UTC by RussellChamp

* save as draft or pending depending on which button was clicked
* fix a bunch of breadcrumbs on pages

2021-09-20 16:46 UTC, RussellChamp commented on src/components/forms/ItemForm.svelte
> +  // then onSubmit is automatically called by the form
so what confused me in the code here was that _REGARDLESS OF WHICH BUTTON IS PRESSED_ the `onSubmit` method is always called. not sure what's up with that...

2021-09-20 16:47 UTC, RussellChamp commented on src/pages/claims.svelte
> +  <Breadcrumb />
all the figmas had breadcrumbs and they were easy to add

2021-09-20 16:48 UTC, RussellChamp commented on src/pages/claims/[claimId].svelte
> +  {#if !item.id }
mirrors what in the item details page

2021-09-20 16:49 UTC, RussellChamp commented on src/pages/claims/[claimId].svelte
> +  {#if !item.id }
the other "changes" is just an indentation change

2021-09-20 16:55 UTC, RussellChamp commented on src/pages/items/[itemId]/edit.svelte
> -const onSaveForLater = async event => {
in either case we're just submitting an item to be created. the form has already specified if it is a 'Draft' or 'Pending' this code is not needed

2021-09-20 18:34 UTC, hobbitronics commented on src/pages/claims/[claimId].svelte
> +import { Button, Page, } from '@silintl/ui-components'
was this comma added intentionally?

2021-09-20 18:45 UTC, hobbitronics commented on src/components/forms/ItemForm.svelte
> +  // then onSubmit is automatically called by the form
I think we were maybe anticipating different endpoints but then things changed.

2021-09-20 18:47 UTC, hobbitronics approved these changes
Looks good.

2021-09-20 20:42 UTC, hobbitronics commented on src/pages/items/[itemId]/edit.svelte
>    await updateItem(policyId, itemId, event.detail)
should we be adding the call to https://s3.amazonaws.com/static.gtis.guru/cover/api-docs.html#operation/PolicyItemsSubmit

2021-09-20 20:53 UTC, hobbitronics requested changes
I think I see the issue. When we are editing a Draft, we need to use the PolicyItemSubmit after updateItem.

2021-09-20 21:54 UTC, forevermatt commented on src/components/forms/ItemForm.svelte
> +  // then onSubmit is automatically called by the form
Ahh, my mistake. I think that means the `on:click={saveForLater}` should have been `on:click|preventDefault={saveForLater}` to prevent that button click from also submitting the form.

2021-09-20 21:56 UTC, forevermatt commented on src/components/forms/ItemForm.svelte
> +  coverageStatus = 'Draft'
I don't think we get to set the status directly. We create the item (which automatically results in it being in a Draft state), and then also (if they were ready to submit it for coverage) call the [PolicyItemsSubmit](https://static.gtis.guru/cover/api-docs.html#operation/PolicyItemsSubmit) endpoint.

2021-09-20 22:02 UTC, forevermatt commented on src/pages/claims/[claimId]/edit.svelte
> +$: breadcrumbLinks = [claimsBreadcrumb, thisClaimBreadcrumb, editBreadcrumb]
This isn't any criticism of your work here, @RussellChamp, I'm just wondering...

It seems like we're ending up needing to duplicate a fair bit of code for the dynamic breadcrumbs. What if we tweak the Breadcrumbs component to simply take another parameter for an additional (non-link) item at the end of the breadcrumbs, for representing the current page? It seems odd to me to have a link in the breadcrumbs to the page the user is currently on, so we could simply remove that from the list of auto-generated links.

Thoughts?

2021-09-21 13:03 UTC, RussellChamp commented on src/pages/claims/[claimId].svelte
> +import { Button, Page, } from '@silintl/ui-components'
no.

2021-09-21 13:04 UTC, RussellChamp commented on src/pages/claims/[claimId]/edit.svelte
> +$: breadcrumbLinks = [claimsBreadcrumb, thisClaimBreadcrumb, editBreadcrumb]
i do not feel strongly one way or another about this

2021-09-21 13:59 UTC, forevermatt commented on src/pages/items/[itemId]/edit.svelte
> -const onSaveForLater = async event => {
I think this will be needed...

2021-09-21 14:00 UTC, forevermatt commented on src/pages/items/[itemId]/edit.svelte
> -const onSaveForLater = async event => {
Oh, this is for editing an item. Hmm... yeah, you could well be right. I think we will need the separate "save-for-later" handler when creating a new item, though (below).

2021-09-21 14:03 UTC, forevermatt commented on src/components/forms/ItemForm.svelte
> +  dispatch('submit', getFormData())
This should be 'save-for-later'
```suggestion
  dispatch('save-for-later', getFormData())
```

2021-09-21 14:04 UTC, forevermatt commented on src/components/forms/ItemForm.svelte
> +  event.preventDefault()
Let's use [Svelte's way of the prevent-default](https://svelte.dev/tutorial/event-modifiers), rather than calling this manually, if you don't mind

2021-09-21 14:05 UTC, RussellChamp commented on src/components/forms/ItemForm.svelte
> +  dispatch('submit', getFormData())
i removed that event. do you think i should add it back?

2021-09-21 14:06 UTC, RussellChamp commented on src/components/forms/ItemForm.svelte
> +  event.preventDefault()
i was getting some warning squiggly when trying to do it that way and thought i did something wrong
![image](https://user-images.githubusercontent.com/242294/134185900-0bbb1296-7c98-4159-8b5a-2e114d8d3921.png)

2021-09-21 14:57 UTC, merged