Use policyId from the url for everything
silinternational/cover-ui pull request #250
Opened 2021-11-02 14:19 UTC by RussellChamp

* Create a readable store for policyId that automatically updates when the url changes
* Use selectedPolicyId instead of $user.policy_id on appropriate pages
* Use this store to create derived stores for selectedPolicy, selectedPolicyItems, selectedPolicyClaims and use them as appropriate instead of manually figuring that out in each component

2021-11-02 14:21 UTC, RussellChamp commented on src/components/ItemsTable.svelte
> +import ItemDeleteModal from './ItemDeleteModal.svelte'
resolves a 'circular dependency' issue. when in a component, DO NOT import from the 'components' index

2021-11-02 14:22 UTC, RussellChamp commented on src/components/RoleAndPolicyMenu.svelte
> -const tryToSetInitialRolePolicySelection = (
do not manually set the policyId. we get that from the route and policyId store

2021-11-02 14:23 UTC, RussellChamp commented on src/components/RoleAndPolicyMenu.svelte
> +  if (myPolicies.some((p) => p.id === policyId)) {
i changed some of the assumptions here. does this still fit the initial understanding?

2021-11-02 14:43 UTC, forevermatt commented on src/components/RoleAndPolicyMenu.svelte
> +  recordRoleSelection(userRole)
This looks like a bug: selecting a policy used to force the role to be "User" (aka "Customer")... it may be helpful for you to walk me/us through your changes, to help us see the big picture design now.

2021-11-02 14:45 UTC, forevermatt commented on src/components/RoleAndPolicyMenu.svelte
> +      label: policy.household_id || 'Household',
When we get to real data, the `household_id` will just be a 6-digit number, so probably leaving this as always "Household" (until we have a better option) would be good at this point.

2021-11-02 14:46 UTC, forevermatt commented on src/components/RoleAndPolicyMenu.svelte
> -const tryToSetInitialRolePolicySelection = (
Okay. We'll need some way to set a customer's initial policy ID to their first Corporate policy, or if they don't have one, to their Household policy, though.

2021-11-02 14:50 UTC, RussellChamp commented on src/pages/steward/home.svelte
>  $: dependents = [].concat(...Object.values($dependentsByPolicyId))
we can do the same to these later

2021-11-02 14:50 UTC, forevermatt commented on src/components/RoleAndPolicyMenu.svelte
> +  if (myPolicies.some((p) => p.id === policyId)) {
Hmm... I think it would be preferable for an admin to always start as their admin role, for consistency's sake. They'll know/learn how to switch to acting as a Customer, but that will be far less often than their desire to act as an admin, I would think.

2021-11-02 14:54 UTC, RussellChamp commented on src/components/RoleAndPolicyMenu.svelte
> +export let role: UserAppRole
`undefined` is kinda an implicitly understood value for types but you usually only say it explicitly if you want to allow the value to be _assigned_ undefined.
eg if you wanted to be able to say `role = undefined` (which isn't the case here).

2021-11-02 15:16 UTC, RussellChamp commented on src/components/RoleAndPolicyMenu.svelte
> +  recordRoleSelection(userRole)
i can see how you'd think that. i can rework this.

2021-11-02 15:21 UTC, RussellChamp commented on src/components/RoleAndPolicyMenu.svelte
> -const tryToSetInitialRolePolicySelection = (
i defaulted to what the $user.policy_id has

2021-11-02 15:27 UTC, RussellChamp commented on src/components/RoleAndPolicyMenu.svelte
> +      label: policy.household_id || 'Household',
changed

2021-11-02 15:27 UTC, RussellChamp commented on src/components/RoleAndPolicyMenu.svelte
> +  if (myPolicies.some((p) => p.id === policyId)) {
changed

2021-11-02 15:52 UTC, RussellChamp commented on src/components/RoleAndPolicyMenu.svelte
> -const tryToSetInitialRolePolicySelection = (
This is the only open "issue" on this PR that can maybe be resolve in the next one

2021-11-02 17:05 UTC, forevermatt commented on src/components/RoleAndPolicyMenu.svelte
> +export let role: UserAppRole
Ohhh... okay, thanks.

2021-11-02 17:07 UTC, forevermatt commented on src/components/RoleAndPolicyMenu.svelte
> +$: setInitialRoleSelection(role)
Oh, clever. Since the `role` will presumably only change once (when the `/users/me` call comes back), then this will effectively only be called twice: once when `role` is undefined, and once when it has a real value.

2021-11-02 19:50 UTC, forevermatt requested changes
Several comments added (sorry), but I would only consider a couple of them blockers.

2021-11-02 19:50 UTC, forevermatt commented on src/pages/policies/[policyId]/claims/[claimId].svelte
> +export let policyId = $selectedPolicyId
Would there be a benefit to no longer exporting this property? As-is, it's value could come through two different routes, which feels concerning.

2021-11-02 19:50 UTC, forevermatt commented on src/pages/policies/[policyId]/claims/[claimId].svelte
> +$: isMemberOfPolicy = memberBelongsToPolicy($user.id, $policies, item.policy_id)
It looks like this page can get its Policy ID from three different sources:
1. from routify injecting it (`export let policyId...`),
2. from our store (`... let policyId = $selectedPolicyId`), or
3. from an item (`memberBelongsToPolicy(..., ..., item.policy_id)`, derived from the claimId in the URL).

If we can reduce the number of places we look for a Policy ID, I think it will reduce odd bugs and ease troubleshooting.
```suggestion
$: isMemberOfPolicy = memberBelongsToPolicy($user.id, $policies, policyId)
```

Thoughts?

2021-11-02 19:50 UTC, forevermatt commented on src/pages/policies/[policyId]/settings.svelte
> +  <Button prependIcon="add" url={addDependentUrl} outlined>Add dependent</Button>
I like how you did this: getting the policy-specific URL above, then passing it to the Button (rather than using a click event).

2021-11-02 19:50 UTC, forevermatt commented on src/pages/policies/[policyId]/settings/dependents/new.svelte
> +  await addDependent(policyId, formData)
Nice fix

2021-11-02 19:50 UTC, forevermatt commented on src/pages/settings.svelte
> +$: $user.policy_id && $redirect(settingsPolicy($user.policy_id))
This may end up needing to use `$selectedPolicyId`, so that if a customer is viewing one of their corporate policies, this will go to that policy's settings.

2021-11-02 19:50 UTC, forevermatt commented on src/pages/steward/home.svelte
>  $: dependents = [].concat(...Object.values($dependentsByPolicyId))
Agreed, though we might even be able to refactor these out at some point. I think they're just here to try to ensure the admin has all the related data, for populating their ClaimCards.

2021-11-03 14:17 UTC, RussellChamp commented on src/data/policies.ts
> +  return policies.find((p) => p.id === selectedPolicyId) || policies[0] || {}
fixed

2021-11-03 14:18 UTC, RussellChamp commented on src/data/policies.ts
> +  const member = policy?.members?.find((m) => m.id === memberId)
gonna keep it this way. i don't think there is a performance difference and this helps when debugging

2021-11-03 14:22 UTC, RussellChamp commented on src/pages/policies/[policyId]/claims/[claimId].svelte
> +$: isMemberOfPolicy = memberBelongsToPolicy($user.id, $policies, item.policy_id)
fixed. i was trying to think if there was any case when the api might return us policy items where the policy_id is not what we just retrieved from. probably not worthwhile worrying about. :)

2021-11-03 14:35 UTC, RussellChamp commented on src/pages/_layout.svelte
> +$: myPolicies = $policies.filter((p) => p.members?.some((m) => m.id === $user.id))
resolved. had to add policies to the user type

2021-11-03 14:37 UTC, RussellChamp commented on src/pages/settings.svelte
> +$: $user.policy_id && $redirect(settingsPolicy($user.policy_id))
no, this is the "shortcut" route when a policy isn't specified at all. we want to default to something in that case

2021-11-03 14:58 UTC, forevermatt approved these changes

2021-11-03 14:59 UTC, merged