Fix `isLoadingById()`
silinternational/cover-ui pull request #254
Opened 2021-11-02 20:52 UTC by forevermatt

### Fixed
- Refactor isLoadingById() data to use relative API paths
- Fix usage of isLoadingById() to have correct paths and react better

2021-11-02 23:05 UTC, hobbitronics approved these changes
Ya fixed it!

2021-11-03 13:14 UTC, RussellChamp requested changes

2021-11-03 13:14 UTC, RussellChamp commented on src/pages/policies/[policyId]/claims/[claimId]/edit.svelte
> +{#if $loading && isLoadingById(`claimss/${claimId}`)}
personally i don't think we should be hand-coding the uri like this as it requires your component to be aware of the API implementation. it also allows for typos like the above `claimss` vs `claims`

2021-11-03 14:22 UTC, forevermatt commented on src/pages/policies/[policyId]/claims/[claimId]/edit.svelte
> +{#if $loading && isLoadingById(`claimss/${claimId}`)}
Agreed. We'll refactor this later. 👍

2021-11-03 14:25 UTC, RussellChamp approved these changes

2021-11-03 14:26 UTC, merged