Feat/add policy items to cards grid
silinternational/cover-ui pull request #280
Opened 2021-11-08 19:43 UTC by RussellChamp

* Create a CardsGrid component that includes data for both claims and policy items
* Populate with data from recent activity endpoint

This PR introduced the TypeScript concept of [type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) (or type guards). This is quite useful when working with arrays of data that could contain multiple types (such as the store we use for recent activity)

2021-11-08 19:45 UTC, RussellChamp commented on src/components/CardsGrid.svelte
> +      {#if isClaimItem(item.data)}
using the type predicate here means that the compiler can now reason about what the concrete type of your variable actually is. in the below code, the compiler is able to figure out that the `item.data` in the first block is actually a `ClaimItem` and the one in the else block is a `PolicyItem`. yay!

2021-11-08 21:01 UTC, hobbitronics commented on src/data/claims.ts
> +export function isClaimItem(obj: any): obj is ClaimItem {
just checking you was "obj is ClaimItem" as I am used to seeing "as" but then is seems you are returning a boolean so maybe "is" is correct.

2021-11-08 21:49 UTC, forevermatt commented on src/components/ItemCard.svelte
> +  <ClaimCardBanner {statusReason} {state} {showRevisionMessage} />
This would probably be best done in a separate PR, but if `ClaimCardBanner` is truly general-purpose enough to work both for a ClaimCard and for an ItemCard, let's rename it to `CardBanner` to avoid confusion and reduce potential bugs.

2021-11-08 22:51 UTC, forevermatt reviewed
I'd like your input on a few things before this is merged.

2021-11-08 22:51 UTC, forevermatt commented on src/data/recent-activity.ts
> +export function isRecentClaim(obj: any): obj is RecentClaim {
In the docs on type predicates, they use type unions as the argument type. Is there an advantage to using `any` here rather than `RecentChange`?

(Similarly below on `isRecentItem(obj: any)`)

2021-11-08 22:51 UTC, forevermatt commented on src/data/recent-activity.ts
> +export const recentActivity = writable<RecentActivity>()
What was the advantage of splitting out a separate `recentActivity` store instead of only having a `recentChanges` store?

(If it's worth staying with this split--which it may well be--would you mind if we don't export `recentActivity`? It seems helpful to hide the messiness within this single file, and only expose the sorted list of `recentChanges` so that anywhere we use it, we always use that sorted list.)

2021-11-08 22:51 UTC, forevermatt commented on src/components/CardsGrid.svelte
> +const getRecentChanges = (changes: RecentChange[]): CardItem[] => {
(This comment only applies if it is still beneficial to have a separate `CardItem` type--see comment above):

Though this is named `getRecentChanges()`, it looks like it's actually being given `RecentChange`s and is getting back `CardItem`s.

What would you think of renaming it to indicate that what we're actually getting back is `CardItem`s?

2021-11-08 22:51 UTC, forevermatt commented on src/data/claims.ts
> +export function isClaimItem(obj: any): obj is ClaimItem {
Yeah, I think [the docs](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) that @RussellChamp linked to give a nice explanation of that, which helped me take a couple of steps forward in my understanding of this syntax.

2021-11-08 22:51 UTC, forevermatt commented on src/components/CardsGrid.svelte
> +type CardItem = { data: ClaimItem | PolicyItem; claim?: Claim }
I'm still having trouble understanding the benefit of adding a new `CardItem` type, rather than just using `RecentChange[]` for the could-be-either type that we're passing around. Mind elaborating on that?

(I feel like we're getting enough types that are similar, but not quite identical, that it's getting harder to follow, and so I was wondering about reducing that.)

2021-11-09 14:53 UTC, RussellChamp commented on src/components/CardsGrid.svelte
> +type CardItem = { data: ClaimItem | PolicyItem; claim?: Claim }
the list of cards can be hydrated either through passing it the list of recent changes OR by passing it a list of claims and policy items. while i could mash the claims/items into the format of `RecentChange[]` I'd rather not since there are some values that I do not have (like 'StatusUpdatedAt').

2021-11-09 14:53 UTC, RussellChamp commented on src/data/items.ts
> +export const incompleteItemCoverageStatus = [
huh....... so i looked it up to make sure i did it right and it appears that 'status' can serve as both singular and plural. https://grammarhow.com/plural-of-status/ Thoughts on that?

2021-11-09 14:53 UTC, RussellChamp commented on src/data/recent-activity.ts
> +export function isRecentClaim(obj: any): obj is RecentClaim {
in the examples, they are limiting the scope of their `isFooType` to only ever differentiate between the supplied union types. by using an `any` I am saying "pass me in anything at all and i'll tell you if it is a RecentClaim". this is more flexible but also potentially vulnerable to false positives since `{ Claim: 'foo', StatusUpdatedAt: 'bar', anythingElseIWant: 42 }` will also be classified as a 'RecentClaim'. i think this is a worthwhile tradeoff

2021-11-09 14:53 UTC, RussellChamp commented on src/data/recent-activity.ts
> +export const recentActivity = writable<RecentActivity>()
while working on CardsGrid I initially was using the raw RecentActivity before switching over. part of the reasoning was to keep the logic of loadRecentActivity cleaner by moving data munging into a helper function (in this case, the derived state). an additional benefit is that we do not pay the computational cost of the data munging on retrieval time but only when there is an actual subscriber to the data store.
but i can appreciate the desire to expose a unified interface and will remove the export on recentActivity

2021-11-09 14:59 UTC, forevermatt commented on src/components/CardsGrid.svelte
> +type CardItem = { data: ClaimItem | PolicyItem; claim?: Claim }
What if we simply extracted the PolicyItems and Claims from the RecentChanges, so that in both cases we're simply passing in PolicyItems and Claims?

2021-11-09 15:01 UTC, RussellChamp commented on src/components/CardsGrid.svelte
> +type CardItem = { data: ClaimItem | PolicyItem; claim?: Claim }
because RecentChanges has already mashed the two together into a single array

2021-11-09 15:27 UTC, hobbitronics requested changes
Looks like some new (to me) typescript magic and I see you used uniq from lodash. Fun stuff. I noticed the derived stores didn't have $ when referencing other stores so I made suggestions to fix that. Otherwise looks good.

2021-11-09 15:27 UTC, hobbitronics commented on src/data/dependents.ts
> +  return Object.values(dependentsByPolicyId).flat()
```suggestion
  return Object.values($dependentsByPolicyId).flat()
```

2021-11-09 15:27 UTC, hobbitronics commented on src/data/dependents.ts
> +export const allPolicyDependents = derived(dependentsByPolicyId, (dependentsByPolicyId) => {
```suggestion
export const allPolicyDependents = derived(dependentsByPolicyId, ($dependentsByPolicyId) => {
```

2021-11-09 15:27 UTC, hobbitronics commented on src/data/recent-activity.ts
> +export const recentChanges = derived(recentActivity, (recentActivity) => {
```suggestion
export const recentChanges = derived(recentActivity, ($recentActivity) => {
```

2021-11-09 15:27 UTC, hobbitronics commented on src/data/recent-activity.ts
> +  if (!recentActivity) return []
```suggestion
  if (!$recentActivity) return []
```

2021-11-09 15:27 UTC, hobbitronics commented on src/data/policies.ts
>  export const selectedPolicy = derived([policies, selectedPolicyId], ([policies, selectedPolicyId]) => {
when other stores are referenced in a derived store they should be prepended with a $
```suggestion
export const selectedPolicy = derived([policies, selectedPolicyId], ([$policies, $selectedPolicyId]) => {
```

2021-11-09 15:27 UTC, hobbitronics commented on src/data/policies.ts
> +  return policies.find((p) => p.id === selectedPolicyId) || ({} as Policy)
```suggestion
  return $policies.find((p) => p.id === $selectedPolicyId) || ({} as Policy)
```

2021-11-09 15:27 UTC, hobbitronics commented on src/data/recent-activity.ts
> +  recentActivity.set(result)
I am confused why this chunk of code got moved down here.

2021-11-09 15:29 UTC, RussellChamp commented on src/data/recent-activity.ts
> +  return !!((obj as RecentClaim)?.Claim && (obj as RecentClaim)?.StatusUpdatedAt)
we're basically saying "if the random object we were passed has a 'Claim' and a 'StatusUpdatedAt' then it's a duck, er, it's a RecentClaim.

2021-11-09 15:33 UTC, RussellChamp commented on src/data/dependents.ts
> +export const allPolicyDependents = derived(dependentsByPolicyId, (dependentsByPolicyId) => {
addressed all the instances

2021-11-09 15:38 UTC, RussellChamp commented on src/data/recent-activity.ts
> +export function isRecentClaim(obj: any): obj is RecentClaim {
in this case we are trying to determine if the arbitrary passed in object is, in fact, a 'RecentClaim' or not. they are guilty until proven innocent so 'obj' seemed more appropriate.

2021-11-09 15:38 UTC, RussellChamp commented on src/data/recent-activity.ts
> +  recentActivity.set(result)
i basically moved the data munging out of the loadRecentActivity function

2021-11-09 15:41 UTC, hobbitronics commented on src/data/claims.ts
> +export function isClaimItem(obj: any): obj is ClaimItem {
ahh thanks.

2021-11-09 15:49 UTC, forevermatt commented on src/components/CardsGrid.svelte
> +$: items = recentChanges.length ? parseRecentChanges(recentChanges) : parseClaimsAndPolicyItems(claims, policyItems)
Would you be okay with renaming this `items` to `cardItems`? The rest of the codebase uses `items` to refer to PolicyItems, and I think it will be helpful to clarify here that this is CardItems.

2021-11-09 15:53 UTC, hobbitronics approved these changes
Thanks for clarifying some things for me. Fun fact, if we weren't using lodash we could still use `uniqueArr = [...new Set(arr)]` instead of uniq. Not sure which is faster.

2021-11-09 15:53 UTC, hobbitronics commented on src/data/recent-activity.ts
> +export function isRecentClaim(obj: any): obj is RecentClaim {
ok ok, I see now.

2021-11-09 15:53 UTC, hobbitronics commented on src/data/recent-activity.ts
> +  return !!((obj as RecentClaim)?.Claim && (obj as RecentClaim)?.StatusUpdatedAt)
oh cool. Makes perfect sense when I look at it now.

2021-11-09 15:53 UTC, hobbitronics commented on src/data/recent-activity.ts
> +  recentActivity.set(result)
ok, I was being confused by the PR review view I was using in github.

2021-11-09 15:54 UTC, forevermatt commented on src/data/recent-activity.ts
> +export function isRecentClaim(obj: any): obj is RecentClaim {
That works

2021-11-09 15:54 UTC, forevermatt commented on src/components/CardsGrid.svelte
> +export let recentChanges: RecentChange[] = []
This can totally be a change for a later PR, but I'd like us to push the `RecentChanges` concept back up out of this `CardsGrid` component, to decouple those two concepts.

This CardsGrid is great, and it simply needs to have a list of claims (technically, claim items with some claim data) and a list of policy items in order to do it's thing.

At the moment, we're using the RecentChanges data to as an available source of that data for admins, which we would otherwise lack right now. That works, but I think it would help reduce coupling and complexity to avoid letting that implementation detail (that we're using recent changes) leak into this component's code.

2021-11-09 15:56 UTC, forevermatt commented on src/data/items.ts
> +export const incompleteItemCoverageStatus = [
Let's go with "statuses", as it's unambiguous.

2021-11-09 16:21 UTC, merged