add freshdesk widget and types
silinternational/cover-ui pull request #284
Opened 2021-11-09 18:30 UTC by RussellChamp

* adds the freshdesk widget along with some hand-written types
* populates the feedback form with the current user's name and email

2021-11-09 18:32 UTC, RussellChamp commented on src/components/FreshdeskWidget.svelte
> +  if (user && typeof FreshworksWidget !== 'undefined') {
this was necessary because our empty user store loads before the FreshworksWidget is setup.
There are probably timing hisenbugs hidden here but the works case scenario is that the widget doesn't get properly pre-populated with the current user name and email.

2021-11-09 18:34 UTC, RussellChamp commented on src/customTypes/freshdesk.d.ts
> +declare function FreshworksWidget(command: 'hide', target?: 'launcher'): void
i read through their entire widget usage API documentation and this seems like all the commands they support. i got lazy near the end but i don't expect we're actually gonna call a lot of these.

2021-11-09 19:07 UTC, forevermatt commented on src/components/FreshdeskWidget.svelte
> +  window.fwSettings = { widget_id: 73000000445 }
It would probably be better to pass in the FreshDesk Widget ID via an environment variable.

2021-11-09 19:16 UTC, forevermatt requested changes

2021-11-09 19:16 UTC, forevermatt commented on src/components/FreshdeskWidget.svelte
> +  <script type="text/javascript" src="https://widget.freshworks.com/widgets/73000000445.js" async defer></script>
Note that the Widget ID (if made dynamic) would need to be injected here, too.

2021-11-09 19:16 UTC, forevermatt commented on src/customTypes/freshdesk.d.ts
> +  Low = 1,
Does this syntax then cause the subsequent entries to have consecutive values (e.g. Medium: 2, etc.)?

2021-11-09 19:16 UTC, forevermatt commented on src/customTypes/freshdesk.d.ts
> +declare function FreshworksWidget(command: 'close' | 'destory' | 'boot'): void
```suggestion
declare function FreshworksWidget(command: 'close' | 'destroy' | 'boot'): void
```

2021-11-10 14:24 UTC, RussellChamp commented on src/customTypes/freshdesk.d.ts
> +  Low = 1,
yes https://www.typescriptlang.org/docs/handbook/enums.html

2021-11-10 15:16 UTC, forevermatt commented on .env.example
> +FRESHDESK_ID=73000000445
Sorry to ask for one more change, but let's avoid putting any real IDs in our repo. Would you mind doing something similar with this to what we did with the Google Analytics ID, above?

2021-11-10 15:27 UTC, forevermatt approved these changes

2021-11-10 15:31 UTC, merged