refactor data services
silinternational/cover-ui pull request #319
Opened 2021-11-15 18:01 UTC by RussellChamp

* the goal is to abstract business logic from the data access layer
* give more concrete typings to what's getting passed around
* this could probably use even a bit more massaging

2021-11-15 20:06 UTC, forevermatt requested changes

2021-11-15 20:06 UTC, forevermatt commented on src/data/claims.ts
> +export type ClaimItemDetailsData = {
From the name, it's not obvious to me what this data type represents. Based on usage, it appears to be sort of a "ClaimItem form data" object, or would be if we had a `<ClaimItemForm/>` component.

Is that correct? If so, would renaming it to `ClaimItemFormData` fit the intended usage?

2021-11-15 20:06 UTC, forevermatt commented on src/data/claims.ts
> +export async function createClaim(item: PolicyItem, claimData: CreateClaimRequestBody): Promise<Claim> {
I think this change starts to get at the heart of the code design issues we're hitting here, as it pushes API-named variables out into the rest of our UI code. The benefit of doing the mapping here within this function is that it provides a clear, expected place to find the mapping between UI variable names and API variable names, and lets more of our UI code just use UI variable names.

I'm going to hold off on reviewing more of this PR until we address that design decision (of how to handle API variable names vs. UI variable names for the same data).

2021-11-16 14:45 UTC, RussellChamp commented on src/components/forms/DependentForm.svelte
> +const dispatch = createEventDispatcher<{ cancel: void; remove: string; submit: PolicyDependent }>()
using types in this way helps to set up a data "contract" between the producer and consumer of those events. If I change the data included in that event (intentionally or accidentally), the IDE will make it abundantly clear.
![image](https://user-images.githubusercontent.com/242294/142005387-771a30de-b106-4fb6-9831-a8861f67079c.png)
On the consumer side, it also gives an immediate understanding of what data will be emitted from a component event without requiring you to manually interrogate that component and read the code yourself.
![image](https://user-images.githubusercontent.com/242294/142005775-a85fe641-36d2-40ad-b653-192be0b9d216.png)
In the specific cases of this project, we only actually use our components in one or two places of the application so I can appreciate the concern of benefit-to-cost; in the case where they are used dozens of times, this practice becomes insanely beneficial. I made these changes in this PR because they helped me understand the flow of data while refactoring components. Without them, 'any' data was being passed by the producer and 'any' data was being received by the consumer so it was difficult to track how the refactor affected things.

2021-11-16 14:50 UTC, RussellChamp commented on src/components/forms/DependentForm.svelte
> +  assertHas(dependent?.name, 'Please specify a name')
i was trying to reduce the number of in-between variable that were doing nothing more than translate one caseing style to another. this might not have been the best approach for me to take. :/ In the limited testing I did, there was not any data leakage (although i've hit those issues before!!)

2021-11-16 14:56 UTC, RussellChamp commented on src/components/forms/DependentForm.svelte
> +    dependent.child_birth_year = 0
you say "leaking" but my thought was data consistency. if the BE says 'None' and the FE says 'empty string' (for eg) it will cause us issues when checking for values or doing comparisons, etc. granted, this may not be the best way to achieve that.
However, when retrieving the list of corporate dependents, they are marked as having a birth year of '0' and relationship of 'None'
![image](https://user-images.githubusercontent.com/242294/142008744-885e481d-fdcb-41cf-89b1-da29c565f714.png)

2021-11-16 14:58 UTC, RussellChamp commented on src/pages/policies/[policyId]/claims/[claimId].svelte
> +      is_repairable: updatedClaimItemData.isRepairable,
i agree with you on this one. it needs more work

2021-11-16 15:00 UTC, RussellChamp commented on src/data/claims.ts
> +export type ClaimItemDetailsData = {
yeah, i was probably lazy with the naming here

2021-11-16 15:13 UTC, RussellChamp commented on src/data/claims.ts
> +export async function createClaim(item: PolicyItem, claimData: CreateClaimRequestBody): Promise<Claim> {
i take a slightly different stance. the 'any' is a far cry from being 'clear and expected'. in my experience writing data service layers, the data service should be as PURE as possible without doing too much data munging. Otherwise you run the risk of callers having to boff their perfectly good data so that your data service can just biff it back. (Eg If I have valueInCents that i have to convert to formValueInUSD before calling updateThing() which converts it back into valueInCents)
A happy middle ground would be to write some helper functions for serializing and reserializing data values. These could be called after a GET and before a PUT/POST. The data services will be a little 'messier' but hopefully the data transformation process occurs in only one place. Another benefit of breaking them out means that whenever-it-actually-happens unit testing will be easier to perform.

2021-11-16 15:39 UTC, forevermatt commented on src/components/forms/DependentForm.svelte
> +const dispatch = createEventDispatcher<{ cancel: void; remove: string; submit: PolicyDependent }>()
Ahhh... thanks! I hadn't yet seen any of those benefits in my IDE, but that does seem quite worthwhile. Okay, great. I'm good with typing those now. 👍

2021-11-16 15:42 UTC, forevermatt commented on src/components/forms/DependentForm.svelte
> +  assertHas(dependent?.name, 'Please specify a name')
Gotcha. Yeah, in this case it's more about preventing in-form changes from being reflected outside of the form than about translating field names.

If we're not passing in the `dependent` via `bind:dependent={dependent}` then we might not experience that problem, but it still is worth using some other local variable (e.g. `formData`) rather than the object passed in so that consuming code doesn't break if they happen to use `bind:`.

2021-11-16 15:47 UTC, forevermatt commented on src/components/forms/DependentForm.svelte
> +    dependent.child_birth_year = 0
Data consistency definitely has value, so that's worth considering. I hesitate to go with `'None'` and `0` because it's data consistency at the cost of "nonsense" values (if I may use that strong a word). We don't actually mean that the team policy dependent has no relationship with the user. We mean that we have no meaningful data there. We don't actually mean that the dependent was born before 1 A.D., we mean that we have (and use) no meaningful data about their birth year (because it isn't applicable).

If there's a simple way we can get data consistency between front-end code and API responses from the backend that excludes those fields for team policy dependents, that seems (from the UI code perspective) like it would be preferable, though I don't know if that's a reasonable request. Perhaps there's some third option?

2021-11-16 15:54 UTC, forevermatt commented on src/data/claims.ts
> +export async function createClaim(item: PolicyItem, claimData: CreateClaimRequestBody): Promise<Claim> {
Good point on the `any`: that doesn't help us any (😉). A strong type here would definitely have value, but unless the API changes its output/input naming conventions, it looks like it'll need to be something other than `CreateClaimRequestBody`.

You do have good points here, though. Definitely worth discussing and (at least partially) incorporating into our design, though I hesitate to add an entire data-conversion layer.

2021-11-22 17:56 UTC, closed without merging