Use countries list from API
silinternational/cover-ui pull request #332
Opened 2021-11-18 22:01 UTC by forevermatt

### Added
- Add a `countries` svelte store, populated asynchronously when first used

### Changed
- Change "Personal Settings" page to be a searchable-select of a list of countries

---

We'll probably want to extract this to a `<CountrySelector ... />` or something like that if we end up using this in multiple places (such as on the DependentForm). There were just enough details involved that I wouldn't want them replicated throughout our codebase.

2021-11-18 22:40 UTC, hobbitronics commented on src/pages/settings/personal.svelte
> +$: $countries.forEach((country: Country) => (countryOptions[country.name] = country.name))
I am curious what the benefit of using `countryOptions` rather than `$countries` is.

2021-11-18 22:43 UTC, hobbitronics commented on src/pages/settings/personal.svelte
> +$: $countries.forEach((country: Country) => (countryOptions[country.name] = country.name))
nevermind, I see now that `$countries` is an array.

2021-11-18 22:43 UTC, hobbitronics approved these changes
Nice work.

2021-11-19 13:42 UTC, RussellChamp requested changes

2021-11-19 13:42 UTC, RussellChamp commented on src/data/countries.ts
> +  if (!hasLoaded) {
i don't believe this 'hasLoaded' check is necessary. if my understanding of readable is correct, this part should only trigger once

2021-11-19 19:09 UTC, forevermatt commented on src/data/countries.ts
> +  if (!hasLoaded) {
In my testing, it was triggered every time I went to the page that uses it, so I think it is actually beneficial.

2021-11-19 19:41 UTC, merged