add household id form to modal
silinternational/cover-ui pull request #334
Opened 2021-11-19 20:54 UTC by hobbitronics

- Add a householdId form to a modal so users can add it before filling out `ItemForm`

2021-11-19 21:35 UTC, hobbitronics commented on src/pages/policies/[policyId]/items/new.svelte
> +$: $selectedPolicy.type === PolicyType.Household && !$selectedPolicy.household_id && (open = true)
opens the modal if a householdId doesn't exist

2021-11-19 21:36 UTC, hobbitronics commented on src/pages/policies/[policyId]/items/new.svelte
> +  open = false
line 70 is not really necessary as the modal won't open again, but you never know...

2021-11-19 21:40 UTC, hobbitronics commented on src/components/NoHouseholdIdModal.svelte
> +  } else if (!hasSubmitted) {
this last block happens when the Dialog.Alert fires a second time (first is choice) or the user clicks off of the modal (in which case we want them to go back to the previous page).

2021-11-22 15:35 UTC, hobbitronics commented on src/components/NoHouseholdIdModal.svelte
> +let hasSubmitted: boolean = false
rename to hasClosed and use to prevent a second back when user clicks cancel.

2021-11-22 16:51 UTC, forevermatt commented on src/components/NoHouseholdIdModal.svelte
> +const isIdValid = (sanitizedId: string): number | boolean =>
Why is `number` included in this return type? It seems like we want the returned value (i.e. the answer to the question "is this ID valid?") to be just a boolean.

2021-11-22 16:52 UTC, forevermatt commented on src/components/NoHouseholdIdModal.svelte
> +  sanitizedId.length && sanitizedId.split('').every((digit) => /[0-9]/.test(digit))
This might accomplish the "boolean only" goal:
```suggestion
  (sanitizedId.length > 0) && sanitizedId.split('').every((digit) => /[0-9]/.test(digit))
```

2021-11-22 16:56 UTC, forevermatt reviewed
One suggestion, but otherwise looks good.

2021-11-22 17:17 UTC, hobbitronics commented on src/components/NoHouseholdIdModal.svelte
> +const isIdValid = (sanitizedId: string): number | boolean =>
yeah, I was kind of confused by the ts warming since it doesn't seem like it should return -1. We can change it to just boolean but there might be an extra warning.

2021-11-22 17:35 UTC, RussellChamp requested changes
lgtm other than updating the `isIdValid` method

2021-11-22 17:35 UTC, RussellChamp commented on src/components/NoHouseholdIdModal.svelte
> +const isIdValid = (sanitizedId: string): number | boolean =>
the return type was determined to be `number | boolean` because that's exactly what _could_ be returned by the below expression. In the case of an empty string being passed, the expression will resolve as `"".length && "".split()...` => `0 && false` => `0` (which is a numeric value).
To resolve this, you can either change the first expression to `sanitizedId.length > 0` or you can coerce it into a boolean expression with `!!sanitizedId.length`

2021-11-22 18:16 UTC, forevermatt commented on src/components/NoHouseholdIdModal.svelte
> +const isIdValid = (sanitizedId: string): number | boolean =>
Sorry, I should have included this with my previous suggested code change:
```suggestion
const isIdValid = (sanitizedId: string): boolean =>
```

2021-11-22 18:39 UTC, forevermatt commented on src/components/NoHouseholdIdModal.svelte
> +  (sanitizedId.length > 0) && sanitizedId.split('').every((digit) => /[0-9]/.test(digit))
Not at all required, but I wonder if we could have simply done something like this:
```suggestion
const isIdValid = (id: string): boolean => /^[0-9]+$/.test(id)
```

2021-11-22 18:39 UTC, forevermatt approved these changes

2021-11-22 19:04 UTC, hobbitronics commented on src/components/NoHouseholdIdModal.svelte
> +  (sanitizedId.length > 0) && sanitizedId.split('').every((digit) => /[0-9]/.test(digit))
yeah, as long as it works the same i like it better.

2021-11-22 19:40 UTC, merged