Fix "Covered through ___" date
silinternational/cover-ui pull request #353
Opened 2021-12-02 15:17 UTC by forevermatt

## Fixed
- Fix `formatFriendlyDate()` to show the right date regardless of timezone

---

Previously, a date/time string of "2021-12-31" was showing as "12/30/2021" due to timezone issues.

2021-12-02 15:33 UTC, hobbitronics requested changes
can you look at `components/dates.ts` and see if that does the same thing and we should probably combine these files anyways. the formatDate function uses a different method to deal with the utc/local trap, but not sure if these are serving different purposes.

2021-12-03 14:19 UTC, RussellChamp commented on src/helpers/date.ts
> +  if (isJustDate(dateTimeString)) {
we've already included date-fns in the project. does this do the same thing that parseISO would? https://date-fns.org/v2.27.0/docs/parseISO

2021-12-20 18:26 UTC, forevermatt commented
@RussellChamp or @hobbitronics - Is one of you working on resolving/fixing this? As I'm cleaning up old PRs, I saw this one I'd essentially abandoned still sitting here, and I see that the date is still incorrect on production.

2021-12-20 21:22 UTC, hobbitronics commented
> @RussellChamp or @hobbitronics - Is one of you working on resolving/fixing this? As I'm cleaning up old PRs, I saw this one I'd essentially abandoned still sitting here, and I see that the date is still incorrect on production.

No, I haven't been working on it.

2022-01-03 18:09 UTC, hobbitronics commented on src/components/FilePreview/FilePreview.svelte
> -import { Button, Progress } from '@silintl/ui-components'
Button was unused

2022-01-03 18:09 UTC, hobbitronics commented on src/components/ClaimsTable.svelte
> +          <Datatable.Data.Row.Item>{getJustDateFromUTCDateString(claim.incident_date)}</Datatable.Data.Row.Item>
was showing 'Invalid date'

2022-01-03 21:20 UTC, hobbitronics commented on src/components/forms/ClaimForm.svelte
> +  const date = lostDate === todayDateString.split('T')[0] ? todayDateString : lostDate
preserve the full ISOString if today

2022-01-03 21:21 UTC, hobbitronics approved these changes
I approve

2022-01-03 21:25 UTC, Schparky approved these changes

2022-01-03 21:25 UTC, Schparky commented on src/customTypes/@silintl/ui-components.d.ts
> +    value?: string | number
Can this just be `number`?

2022-01-03 21:38 UTC, hobbitronics commented on src/customTypes/@silintl/ui-components.d.ts
> +    value?: string | number
I think so, no new errors if I do.

2022-01-03 21:51 UTC, merged