repairableSelection default to 'repairable
silinternational/cover-ui pull request #378
Opened 2021-12-10 17:53 UTC by hobbitronics

- set claimForm radio button default

2021-12-10 18:00 UTC, Schparky commented
If this is what I think it is, we should revert the API changes that allow `is_repairable` to be `null`

2021-12-13 14:45 UTC, RussellChamp requested changes
left suggestion

2021-12-13 14:45 UTC, RussellChamp commented on src/components/forms/ClaimForm.svelte
> +      : 'repairable'
i lover ternaries but nesting them can quickly become unmaintainable and hard to read. this could be refactored
```suggestion
  repairableSelection =
    typeof claimItem.is_repairable !== 'boolean' ||  claimItem.is_repairable
        ? 'repairable'
        : 'not_repairable'
```

2021-12-13 14:51 UTC, hobbitronics commented
> If this is what I think it is, we should revert the API changes that allow `is_repairable` to be `null`

After we did that change Alex showed me this https://www.nngroup.com/articles/radio-buttons-default-selection/

2021-12-13 15:18 UTC, Schparky commented
> > If this is what I think it is, we should revert the API changes that allow `is_repairable` to be `null`
> 
> After we did that change Alex showed me this https://www.nngroup.com/articles/radio-buttons-default-selection/

Right, which means you will never send `is_repairable` as `null`, right?

2021-12-13 20:18 UTC, hobbitronics commented
> > > If this is what I think it is, we should revert the API changes that allow `is_repairable` to be `null`
> > 
> > 
> > After we did that change Alex showed me this https://www.nngroup.com/articles/radio-buttons-default-selection/
> 
> Right, which means you will never send `is_repairable` as `null`, right?

Correct. The design is to make it a checkbox in the future so that will never be `null` either.

2021-12-13 22:38 UTC, hobbitronics commented on src/data/claims.ts
> +    is_repairable: claimItemData.isRepairable ?? null,
```suggestion
    is_repairable: claimItemData.isRepairable,
```

2021-12-14 17:41 UTC, merged