show different claim states to Signator for Review
silinternational/cover-ui pull request #410
Opened 2022-01-05 18:14 UTC by hobbitronics

Signator:
![image](https://user-images.githubusercontent.com/70765247/148267736-b0eaf9b0-27c0-499e-b5e6-8066b289c1bb.png)
Steward:
![image](https://user-images.githubusercontent.com/70765247/148267783-00b71cf3-65f2-4fe9-80f1-f478082d2f50.png)

2022-01-05 18:30 UTC, Schparky commented on src/components/banners/ClaimBanner.svelte
> +export let roleSelection: UserAppRole
There are other usages of ClaimBanner that probably need to be updated with this new property.

2022-01-05 18:39 UTC, Schparky requested changes
added one change request

2022-01-05 19:08 UTC, hobbitronics commented on src/components/banners/ClaimBanner.svelte
> +export let roleSelection: UserAppRole
I think I will just default to claimStates instead of requiring `roleSelection`

2022-01-05 19:13 UTC, Schparky commented on src/components/banners/ClaimBanner.svelte
> +export let roleSelection: UserAppRole
Does the roleSelection prop need a default? I can't remember if a warning or error is thrown when a component doesn't provide a default value and none is given by its consumer. I seem to remember a console warning.

2022-01-05 20:44 UTC, RussellChamp approved these changes
looks pretty good to me if you resolve schram's issues

2022-01-06 15:28 UTC, hobbitronics commented
> added one change request

No build/console warnings now.

2022-01-06 15:45 UTC, Schparky approved these changes

2022-01-06 15:52 UTC, merged