customer reports
silinternational/cover-ui pull request #454
Opened 2022-02-16 06:16 UTC by hobbitronics

## Add
- month and year consts
- `createReport` function and button to policyDetails view
## Fix 
- bug with createReportModal not opening
Team
![image](https://user-images.githubusercontent.com/70765247/154206503-b051b76b-519a-409d-a22f-86dcfe33ade6.png)
Household (since I am having to purchase coverage and get reimbursed I thought it might be handy)
![image](https://user-images.githubusercontent.com/70765247/154207234-b83a6f00-5c07-4971-89d7-d7d04488a5c5.png)

2022-02-16 06:19 UTC, hobbitronics commented on src/pages/admin/_components/CreateReportModal.svelte
>            <span class="mdc-bold-font">Report Date</span>
The formatter went a bit nuts here. Yours isn't working?

2022-02-16 06:20 UTC, hobbitronics commented on src/pages/admin/_components/CreateReportModal.svelte
> +  on:closed={handleDialog}
modal wasn't opening a second time as parent `modalOpen` wasn't being reset in every case (clicking off modal)

2022-02-16 06:22 UTC, hobbitronics commented on src/pages/policies/[policyId].svelte
> +const onGotoClaim = (event: CustomEvent<Claim>) => $goto(customerClaimDetails(event.detail.policy_id, event.detail.id))
formatter

2022-02-16 06:23 UTC, hobbitronics commented on src/pages/policies/[policyId].svelte
> +    .filter(itemIsApproved)
how should we handle inactive Items? Should I not be filtering them out?

2022-02-16 17:14 UTC, Schparky requested changes
Good work here. Needs a few things, though. See the comments.

2022-02-16 23:37 UTC, hobbitronics commented on src/pages/policies/[policyId].svelte
> +    transactions.map((e: any) => e.join(',')).join('\n') +
since it is just joining arrays I don't think it touches the string contents of them.

2022-02-16 23:39 UTC, Schparky commented on src/pages/policies/[policyId].svelte
> +    transactions.map((e: any) => e.join(',')).join('\n') +
The problem is actually when you load it into a spreadsheet program. The extra commas in the data are read as column separators.

2022-02-16 23:47 UTC, hobbitronics commented on src/pages/policies/[policyId].svelte
> +    transactions.map((e: any) => e.join(',')).join('\n') +
I could wrap the `keys` (1st) element of the array as we don't include commas in the money values.

2022-02-17 01:22 UTC, hobbitronics commented on src/pages/admin/_components/CreateReportModal.svelte
> +import { DateInput, Modal } from 'components'
this seems to be the default way prettier is formatting. I don't think we ever told it to do this.

2022-02-17 01:52 UTC, hobbitronics commented on src/pages/policies/[policyId].svelte
> +function createReport(e: CustomEvent) {
Since we don't have anything to show but a button, I am holding off on its own page.

2022-02-17 02:04 UTC, hobbitronics commented on src/pages/policies/[policyId].svelte
> +    transactions.map((e: any) => e.join(',')).join('\n') +
that's worked

2022-02-17 02:06 UTC, hobbitronics commented on src/pages/policies/[policyId].svelte
> +import CreateReportModal from '../admin/_components/CreateReportModal.svelte'
do you think it would be a good idea to change the modal to describe what kind of report you are getting?

2022-02-17 02:06 UTC, hobbitronics commented on src/pages/policies/[policyId].svelte
> +    .map((item) => [item.name, (item.prorated_annual_premium || item.annual_premium) / -100]) //this is limited to current premiums as the UI doens't see payment dates
probably a good idea

2022-02-17 02:21 UTC, hobbitronics commented on src/pages/policies/[policyId].svelte
> +  const encodedUri = encodeURI(csvContent)
I'm having trouble finding a definitive answer but they do not mention one in the Mozilla docs and the URI seems to be converted to a string first thing. I Tried using some longer strings and it seemed to work fine.

2022-02-17 15:17 UTC, Schparky commented on src/pages/policies/[policyId].svelte
> +import CreateReportModal from '../admin/_components/CreateReportModal.svelte'
Can't hurt. Might even go so far as to say what date range you're including. Or just use two dates instead of a date and a time range (month/year). Using a separate component gives plenty of flexibility to make it unique for this purpose.

2022-02-17 15:19 UTC, Schparky commented on src/pages/policies/[policyId].svelte
> +function createReport(e: CustomEvent) {
I was thinking in terms of code complexity. This function and file are getting hard to read.

2022-02-17 15:20 UTC, Schparky commented on src/pages/policies/[policyId].svelte
> +    .map((item) => [item.name, (item.prorated_annual_premium || item.annual_premium) / -100]) //this is limited to current premiums as the UI doens't see payment dates
Unfortunately, no one is available on the backend team to help with it right now. I'll keep it in mind, though.

2022-02-18 18:27 UTC, Schparky approved these changes
Approved after resolving the comment I added about UI labels. Also, is there a way you could add a disclaimer? Something like "This report may contain data that is not finalized or may be different than your final statement."

2022-02-18 18:27 UTC, Schparky commented on src/components/CustomerReport.svelte
> +  const transactions = reportType === 'Debits' ? premiums : claimPayouts
Technically, premiums can include credits, and claims can include debits. Should the UI labels be "premium" and "claim" instead of "debits" and "credits"?

2022-02-19 01:05 UTC, hobbitronics commented on src/components/CustomerReport.svelte
> +  const transactions = reportType === 'Debits' ? premiums : claimPayouts
good point

2022-02-19 01:47 UTC, merged