add NewCoverageModal to claim view
silinternational/cover-ui pull request #508
Opened 2022-05-12 06:39 UTC by hobbitronics

- Add modal to offer new coverage for replaced items after uploading replace receipt
- create a new item with the old item's data
- send the user to itemEdit to edit the new item

2022-05-16 13:26 UTC, Schparky commented on src/components/NewCoverageModal.svelte
> +  We’re ending coverage for Saxophone since you’ve replaced it. Would you like to cover its replacement?
Did you mean to leave "Saxophone" in here?

2022-05-16 13:29 UTC, Schparky requested changes
Just one change requested. Replace "saxophone" with the actual item name.

2022-05-16 22:26 UTC, hobbitronics commented on src/components/NewCoverageModal.svelte
> +  We’re ending coverage for Saxophone since you’ve replaced it. Would you like to cover its replacement?
woops

2022-05-17 13:37 UTC, Schparky approved these changes

2022-05-17 18:09 UTC, forevermatt approved these changes

2022-05-17 22:38 UTC, merged