improve Inactive Items display in table CVR-654
silinternational/cover-ui pull request #606
Opened 2023-08-31 00:55 UTC by hobbitronics

[CVR-654](https://itse.youtrack.cloud/issue/CVR-654/ItemTable-Improve-display-of-inactive-items)

## Changed
- Inactive.title: 'Not covered'
- refactor sorting to remove complexity from Tables
- show 'Coverage ended' if ended already

2023-08-31 18:29 UTC, forevermatt commented on src/components/Datatable/ItemsTable.svelte
> +            <div class:red={!hasEnded(item)}>
It seems like "will end" (approved with a `coverage_end_date`) and "has ended" (inactive with a `coverage_end_date`) are mutually exclusive conditions.

I think `!hasEnded(item)` will always evaluate to true here.

2023-08-31 18:29 UTC, forevermatt commented on src/components/Datatable/RowItem.svelte
It looks like this new RowItem component can only be used for showing a PolicyItem. Is that correct? If so, is there some way would could make that more readily apparent (such as in the component name or folder somehow)?

If not, that's okay, it was just minimally unexpected in the other diffs where `Datatable.Data.Row.Item` was being replaced by `RowItem` that it was also only available for use with PolicyItems.

2023-08-31 21:30 UTC, hobbitronics commented on src/components/Datatable/ItemsTable.svelte
> +            <div class:red={!hasEnded(item)}>
Good catch!

2023-08-31 21:40 UTC, hobbitronics commented on src/components/Datatable/RowItem.svelte
Yeah, probably best to do that just in case sometime tries using it in ClaimsTable or elsewhere

2023-09-09 01:02 UTC, merchako requested changes
Thank you! I look forward to seeing what y'all choose next for this.

2023-09-10 22:17 UTC, hobbitronics commented on src/components/Datatable/PolicyItems/RowItem.svelte
> +}
This syntax doesn't seem to work. Javascript isn't able to be parsed inside style tags.

2023-09-10 23:46 UTC, merchako commented on src/components/Datatable/PolicyItems/RowItem.svelte
> +}
Please treat it as pseudo code. You can put in a string value instead of the interpolated statement. Or maybe TypescriptSvelte have a way of inserting a value at the compiler level to keep to a single source of truth.

2023-09-11 00:18 UTC, merchako requested changes

2023-09-11 00:18 UTC, merchako commented on src/components/global.css
> +}
I'm hoping we don't have to have such a specific CSS rule in _global.css_. I'm holding out for https://github.com/silinternational/cover-ui/pull/606/files#r1320888519

2023-09-11 00:54 UTC, hobbitronics commented
In order for css classes to be applied to svelte components they need to be
global. Our options are to make a less specific rule (which I was losing
the specificity war on), use :global() within the component file or alter
the Table.Row.Item in ui-components.

On Mon, Sep 11, 2023, 9:48 AM Alex Mercado ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/components/global.css
> <https://github.com/silinternational/cover-ui/pull/606#discussion_r1320894168>
> :
>
> >      display: none !important;
>    }
>  }
> +
> +td.low-contrast.mdc-data-table__cell {
> +  color: var(--mdc-theme-text-secondary-on-light);
> +}
>
> I'm hoping we don't have to have such a specific CSS rule in *global.css*.
> I'm holding out for
> https://github.com/silinternational/cover-ui/pull/606/files#r1320888519
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/silinternational/cover-ui/pull/606#pullrequestreview-1618963240>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ34VP5KYNKWI5P2DYOPO2TXZZKGFANCNFSM6AAAAAA4FJOENA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-11 02:34 UTC, hobbitronics commented on src/components/global.css
> +}
see https://github.com/silinternational/ui-components/pull/221 for possible solution

2023-09-11 16:39 UTC, merchako commented on src/components/Datatable/PolicyItems/RowItem.svelte
> +}
I don't know what the exact value for Inactive would be, but perhaps the result should be something like
```svelte
<Datatable.Data.Row data-coverage-status={item.coverage_status}>
   …
</Datatable.Data.Row>
…
<style>
[data-coverage-status=inactive] .mdc-data-table__cell {
  color: var(--mdc-theme-low-contrast);
}
</style>
```

2023-09-11 21:51 UTC, hobbitronics commented on src/components/Datatable/PolicyItems/RowItem.svelte
> +}
is data-coverage-status a prop? Also is there a way to check for 'disabled' as well?

2023-09-13 15:25 UTC, merchako commented on src/components/Datatable/PolicyItems/RowItem.svelte
> +}
I made up `data-coverage-status`. It isn't yet a prop, but I'm suggesting it could be an attribute on the HTML element (which you'd want to bind to a prop). 

We don't have a concept of being "disabled" on `DataTable` yet, but we could. In your _ui-components_ PR, I suggest using something like `emphasis: string enum` to name and style various cell display states. Disabled is one that I suggest to match the [MDC guide on emphasis](https://m2.material.io/design/color/text-legibility.html#text-backgrounds).

2023-09-14 14:58 UTC, merchako approved these changes

2023-09-15 06:10 UTC, merged