CVR-650 Set statement-name default value
silinternational/cover-ui pull request #608
Opened 2023-08-31 19:30 UTC by forevermatt

[CVR-650](https://itse.youtrack.cloud/issue/CVR-650) Set vehicle name default value

---

### Added
- Add `Vehicle` Risk Category constant
- Set a default value for Statement Name (regardless of category) but let the user customize (i.e. override) it

2023-08-31 19:47 UTC, forevermatt commented on src/data/items.ts
> +  Vehicle = 'Vehicle',
@briskt If we go with this implementation, will we need to add a migration to cover-api to add this new Risk Category to the database? Since that new database record will require a cost_center I assume not (it would be added manually), but wanted to check.

2023-08-31 19:57 UTC, jason-jackson commented on src/data/items.ts
> +  Vehicle = 'Vehicle',
I'd think it would have to unless I'm mistaken.

2023-08-31 20:23 UTC, briskt commented on src/data/items.ts
> +  Vehicle = 'Vehicle',
Yes, it will probably be added by a migration since we don't have any endpoints for managing risk categories. We should also consider adding at least a list endpoint (e.g. `GET /risk-categories`) so the risk category list doesn't have to be hardcoded here.

2023-08-31 21:25 UTC, hobbitronics approved these changes
Lgtm!

2023-08-31 21:25 UTC, hobbitronics commented on src/components/forms/ItemForm.svelte
> +const assembleShortNameExample = (isVehicle, make, model) => {
Nice, want to throw this in itemFormHelpers.ts?

2023-09-01 15:50 UTC, merchako requested changes
The user-given name wins, and the assembled name should be a _default value_, not an example in the helper text. I thought about setting the generated name in the description, but I'd prefer to give specific examples appropriate to each category (TBD). It's generally a good practice to [avoid placeholders](https://www.nngroup.com/articles/form-design-placeholders/), but specifically I want to pre-populate this field because every item *will need* a value here, and I want to set users up to have helpful values by default without having to think up their own.

This is for *all* items, not only vehicles.

Here's what should win:

1. User-given value, if any
2. \`{make} {model} {?year}\`, if unique
3. `{make} {model} {?year} ({uniqueIdentifier.slice(-6)})`

persistentHelperText = "Customize what will appear on your statements"

2023-09-01 15:50 UTC, merchako commented on src/components/forms/ItemForm.svelte
> +      description={'This label will appear on your statements.' + (shortNameExample ? ` Example: ${shortNameExample}` : '')}
```suggestion
      description="Customize what will appear on your statements"
```

2023-09-01 18:49 UTC, forevermatt commented on src/components/forms/ItemForm.svelte
> +      description={'This label will appear on your statements.' + (shortNameExample ? ` Example: ${shortNameExample}` : '')}
That wording fix will be coming in a separate PR (re: [CVR-651](https://itse.youtrack.cloud/issue/CVR-651/Update-ItemForm)). Thanks, though. 👍

2023-09-01 19:19 UTC, briskt commented
> * User-given value, if any
> * `{make} {model} {?year}`, if unique
> * `{make} {model} {?year} ({uniqueIdentifier.slice(-6)})`

@merchako of course the second ("if unique") value will require an API call, and thus a significant amount of complexity. Would it be a problem to skip that and always append the unique identifier if no user-given value is provided?

2023-09-01 19:59 UTC, merchako commented
> Would it be a problem to skip that and always append the unique identifier if no user-given value is provided?

I was wondering about that. Okay, go ahead and skip the API call and always put in the unique ID slice.

2023-09-21 17:31 UTC, forevermatt commented on src/data/items.ts
> +  Vehicle = 'Vehicle',
Okay, good to know the new risk category needs to be added by a migration.

As far as a `GET /risk-categories` endpoint, I don't have an objection per se, but it _is_ still helpful to have it hard-coded here so that we have a TypeScript constant we can use in comparisons in the code. Given that, I don't know whether the risk-categories endpoint gains us anything. Or did I miss some benefit of what you were suggesting?

2023-09-21 17:38 UTC, briskt commented on src/data/items.ts
> +  Vehicle = 'Vehicle',
Just trying to avoid duplication. I guess the only way to truly avoid duplication in some cases is to make a full-stack app.

2023-09-22 20:32 UTC, briskt approved these changes

2023-09-22 20:52 UTC, merchako approved these changes
Looks good to me. Thank you!

2023-09-25 15:10 UTC, merged