npm→bun
silinternational/cover-ui pull request #612
Opened 2023-09-11 22:30 UTC by merchako

Use Bun instead of NPM. It's a lot faster.
requires [installation of bun.sh](https://bun.sh/docs/installation)

2023-09-11 22:34 UTC, hobbitronics requested changes
We need to make sure all the commands work. I haven't been able to get docker to work. I think it would be nice to use bun-bundler.

2023-09-11 22:34 UTC, hobbitronics commented on package.json
> +    "bun-run-all": "^4.1.5",
I don't think this will work

2023-09-11 22:36 UTC, merchako commented on package.json
> +    "bun-run-all": "^4.1.5",
oh whoops!

2023-09-11 22:38 UTC, merchako commented on package.json
> +    "bun-run-all": "^4.1.5",
Resolved in [fd3bf81](https://github.com/silinternational/cover-ui/pull/612/commits/fd3bf817ce7c0470f63e7aa8ac3cb54e3b14d7c7)

2023-09-11 22:59 UTC, hobbitronics commented on package.json
>      "local:dev": "run-p -l build:dev serve:http",
```suggestion
     "local:dev": "conc \"bun run build:dev\" \"bun run serve:http\"",
```

2023-09-11 23:01 UTC, hobbitronics commented on package.json
>      "local:prod": "run-p -l build:prod serve:http",
You'll need `npm i -D concurrently`

2023-09-12 00:01 UTC, briskt commented
I think we need to remove bun.lockb from the repo and add it to .gitignore

2023-09-15 06:05 UTC, hobbitronics commented
I've merged the other bun PR so closing this. Hopefully bun will add more compatibility so we can use it in Docker with Rollup.

2023-09-15 06:05 UTC, closed without merging