CVR-743  add monthly premium to recent claim section
silinternational/cover-ui pull request #654
Opened 2023-10-12 04:26 UTC by hobbitronics

[CVR-743](https://itse.youtrack.cloud/issue/CVR-743/monthly-annual-premiums-in-RecentActivityTable)
- I missed adding this to the recent claims table

2023-10-12 15:02 UTC, briskt approved these changes

2023-10-12 20:20 UTC, forevermatt requested changes

2023-10-12 20:20 UTC, forevermatt commented on src/components/RecentActivityTable.svelte
> +                <small class="tw-opacity-60">({getFormattedClaimItemPremium(recentChange.Claim)}/month)</small>
It looks like this will show the annual premium here as well, rather than the monthly premium. You could just `/ 12` here, but it may be better to set up another function that uses the actual `monthly_premium` field, to ensure we show consistent values (by having the backend do all of that math, to avoid differences in rounding).

2023-10-12 22:13 UTC, hobbitronics commented on src/components/RecentActivityTable.svelte
> +                <small class="tw-opacity-60">({getFormattedClaimItemPremium(recentChange.Claim)}/month)</small>
Good catch

2023-10-13 19:12 UTC, forevermatt approved these changes

2023-10-15 23:04 UTC, merged