Add monthly premiums to policy page
silinternational/cover-ui pull request #655
Opened 2023-10-12 05:56 UTC by hobbitronics

[CVR-705](https://itse.youtrack.cloud/issue/CVR-705/Update-UI-to-handle-monthly-vs-yearly-premiums)
## Added
- Added InfoDialog
- Added Monthly Premium (sum of all) to policy details

![image](https://github.com/silinternational/cover-ui/assets/70765247/68d17288-771a-4582-9662-99a1eaf3ec56)

2023-10-12 15:05 UTC, briskt reviewed
Question and suggestion about monthly premium on policy page.

2023-10-12 15:05 UTC, briskt commented on src/pages/policies/[policyId].svelte
> +        <dt class="tw-flex tw-items-center">
Would it be difficult to hide the monthly premium if a policy has no vehicles? If not, it might be better to omit this since the large majority of policies do not have vehicles.

2023-10-12 20:31 UTC, forevermatt requested changes

2023-10-12 20:31 UTC, forevermatt commented on src/components/InfoModal.svelte
> +<InfoDialog infoIsOpen={open} {title} on:closed={() => (open = false)}>
It looks like both this InfoModal code and the inner InfoDialog code will be setting the InfoDialog's `infoIsOpen` to false when the dialog is closed. Would it be better to only have one of them do it? (Just a question; no request for change here unless you think it's better changed.)

2023-10-12 20:31 UTC, forevermatt commented on src/pages/policies/[policyId].svelte
> +$: monthlyPremiumTotal = formatMoney(approvedItems.reduce((sum, item) => sum + item.monthly_premium, 0))
Unfortunately, I think we'll need to filter the items in both of these lists first by the `billing_period`, because even monthly items have an `annual_premium` value (which equals 12 times their monthly premium), so the `premium` calculation here currently already includes all of the monthly premiums.

I think it's helpful that we have the annual_premium data even for monthly-billed items (e.g. we're using it in the ItemsTable), but that means we have a little "gotcha" to watch our for when doing sums.

2023-10-12 20:31 UTC, forevermatt commented on src/pages/policies/[policyId].svelte
> +        <dt class="tw-flex tw-items-center">
I think it'll be pretty easy to only show this when there _are_ items that are billed monthly. 👍

2023-10-13 19:18 UTC, forevermatt approved these changes

2023-10-15 23:03 UTC, merged